"""
This type stub file was generated by pyright.
"""

from collections.abc import Sequence

"""Command-line implementation of flake8."""

def main(argv: Sequence[str] | None = ...) -> int:
    """Execute the main bit of the application.

    This handles the creation of an instance of :class:`Application`, runs it,
    and then exits the application.

    :param argv:
        The arguments to be passed to the application for parsing.
    """
    ...
