"""
This type stub file was generated by pyright.
"""

import argparse
from typing import (
    Any,
    Callable,
    Dict,
    List,
    Mapping,
    Optional,
    Sequence,
    Tuple,
    Type,
    Union,
)
from flake8.plugins.finder import Plugins

"""Option handling and Option management logic."""
LOG = ...
_ARG = ...
_optparse_callable_map: Dict[str, Union[Type[Any], _ARG]] = ...

class _CallbackAction(argparse.Action):
    """Shim for optparse-style callback actions."""

    def __init__(
        self,
        *args: Any,
        callback: Callable[..., Any],
        callback_args: Sequence[Any] = ...,
        callback_kwargs: Optional[Dict[str, Any]] = ...,
        **kwargs: Any
    ) -> None: ...
    def __call__(
        self,
        parser: argparse.ArgumentParser,
        namespace: argparse.Namespace,
        values: Optional[Union[Sequence[str], str]],
        option_string: Optional[str] = ...,
    ) -> None: ...

class Option:
    """Our wrapper around an argparse argument parsers to add features."""

    def __init__(
        self,
        short_option_name: Union[str, _ARG] = ...,
        long_option_name: Union[str, _ARG] = ...,
        action: Union[str, Type[argparse.Action], _ARG] = ...,
        default: Union[Any, _ARG] = ...,
        type: Union[str, Callable[..., Any], _ARG] = ...,
        dest: Union[str, _ARG] = ...,
        nargs: Union[int, str, _ARG] = ...,
        const: Union[Any, _ARG] = ...,
        choices: Union[Sequence[Any], _ARG] = ...,
        help: Union[str, _ARG] = ...,
        metavar: Union[str, _ARG] = ...,
        callback: Union[Callable[..., Any], _ARG] = ...,
        callback_args: Union[Sequence[Any], _ARG] = ...,
        callback_kwargs: Union[Mapping[str, Any], _ARG] = ...,
        required: Union[bool, _ARG] = ...,
        parse_from_config: bool = ...,
        comma_separated_list: bool = ...,
        normalize_paths: bool = ...,
    ) -> None:
        """Initialize an Option instance.

        The following are all passed directly through to argparse.

        :param short_option_name:
            The short name of the option (e.g., ``-x``). This will be the
            first argument passed to ``ArgumentParser.add_argument``
        :param long_option_name:
            The long name of the option (e.g., ``--xtra-long-option``). This
            will be the second argument passed to
            ``ArgumentParser.add_argument``
        :param default:
            Default value of the option.
        :param dest:
            Attribute name to store parsed option value as.
        :param nargs:
            Number of arguments to parse for this option.
        :param const:
            Constant value to store on a common destination. Usually used in
            conjunction with ``action="store_const"``.
        :param choices:
            Possible values for the option.
        :param help:
            Help text displayed in the usage information.
        :param metavar:
            Name to use instead of the long option name for help text.
        :param required:
            Whether this option is required or not.

        The following options may be passed directly through to :mod:`argparse`
        but may need some massaging.

        :param type:
            A callable to normalize the type (as is the case in
            :mod:`argparse`).  Deprecated: you can also pass through type
            strings such as ``'int'`` which are handled by :mod:`optparse`.
        :param action:
            Any action allowed by :mod:`argparse`.  Deprecated: this also
            understands the ``action='callback'`` action from :mod:`optparse`.
        :param callback:
            Callback used if the action is ``"callback"``.  Deprecated: please
            use ``action=`` instead.
        :param callback_args:
            Additional positional arguments to the callback callable.
            Deprecated: please use ``action=`` instead (probably with
            ``functools.partial``).
        :param callback_kwargs:
            Keyword arguments to the callback callable. Deprecated: please
            use ``action=`` instead (probably with ``functools.partial``).

        The following parameters are for Flake8's option handling alone.

        :param parse_from_config:
            Whether or not this option should be parsed out of config files.
        :param comma_separated_list:
            Whether the option is a comma separated list when parsing from a
            config file.
        :param normalize_paths:
            Whether the option is expecting a path or list of paths and should
            attempt to normalize the paths to absolute paths.
        """
        ...
    @property
    def filtered_option_kwargs(self) -> Dict[str, Any]:
        """Return any actually-specified arguments."""
        ...
    def __repr__(self) -> str: ...
    def normalize(self, value: Any, *normalize_args: str) -> Any:
        """Normalize the value based on the option configuration."""
        ...
    def to_argparse(self) -> Tuple[List[str], Dict[str, Any]]:
        """Convert a Flake8 Option to argparse ``add_argument`` arguments."""
        ...

class OptionManager:
    """Manage Options and OptionParser while adding post-processing."""

    def __init__(
        self,
        *,
        version: str,
        plugin_versions: str,
        parents: List[argparse.ArgumentParser]
    ) -> None:
        """Initialize an instance of an OptionManager.

        :param prog:
            Name of the actual program (e.g., flake8).
        :param version:
            Version string for the program.
        :param usage:
            Basic usage string used by the OptionParser.
        :param parents:
            A list of ArgumentParser objects whose arguments should also be
            included.
        """
        ...
    def register_plugins(self, plugins: Plugins) -> None:
        """Register the plugin options (if needed)."""
        ...
    def add_option(self, *args: Any, **kwargs: Any) -> None:
        """Create and register a new option.

        See parameters for :class:`~flake8.options.manager.Option` for
        acceptable arguments to this method.

        .. note::

            ``short_option_name`` and ``long_option_name`` may be specified
            positionally as they are with argparse normally.
        """
        ...
    def extend_default_ignore(self, error_codes: Sequence[str]) -> None:
        """Extend the default ignore list with the error codes provided.

        :param error_codes:
            List of strings that are the error/warning codes with which to
            extend the default ignore list.
        """
        ...
    def extend_default_select(self, error_codes: Sequence[str]) -> None:
        """Extend the default select list with the error codes provided.

        :param error_codes:
            List of strings that are the error/warning codes with which
            to extend the default select list.
        """
        ...
    def parse_args(
        self,
        args: Optional[Sequence[str]] = ...,
        values: Optional[argparse.Namespace] = ...,
    ) -> argparse.Namespace:
        """Proxy to calling the OptionParser's parse_args method."""
        ...
